CREATE TABLE IF NOT EXISTS Items (id INTEGER PRIMARY KEY AUTOINCREMENT, name CHAR);

CREATE TABLE IF NOT EXISTS Purchase (id INTEGER PRIMARY KEY AUTOINCREMENT, date CHAR, invoice CHAR, item CHAR, quantity INTEGER);

CREATE TABLE IF NOT EXISTS Sale (id INTEGER PRIMARY KEY AUTOINCREMENT, date CHAR, invoice CHAR, item CHAR, quantity INTEGER);